apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: obscuranervosa-com-tls
spec:
  secretName: obscuranervosa-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: obscuranervosa.com
  dnsNames:
    - obscuranervosa.com
    - www.obscuranervosa.com
