name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true rallycoding/react-test npm test

      - name: Set Identity Provider
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/367718748863/locations/global/workloadIdentityPools/github/providers/my-repo"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: multi-k8s-471519

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: multi-cluster
          location: us-central1-c
          project_id: multi-k8s-471519 # Add this line!
      - name: Build
        run: |-
          docker build -t rallycoding/multi-client:latest -t rallycoding/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t rallycoding/multi-server:latest -t rallycoding/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t rallycoding/multi-worker:latest -t rallycoding/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push rallycoding/multi-client:latest
          docker push rallycoding/multi-server:latest
          docker push rallycoding/multi-worker:latest

          docker push rallycoding/multi-client:${{ env.SHA }}
          docker push rallycoding/multi-server:${{ env.SHA }}
          docker push rallycoding/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=rallycoding/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=rallycoding/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=rallycoding/multi-worker:${{ env.SHA }}
